symbol: "EURUSD"
timeframe: "1h"
data:
  years_back: 3
  tz: "America/Bogota"
features:
  window: 32
  indicators:
    atr: 14
    rsi: 14
    ma_fast: 10
    ma_slow: 30
    bb_period: 20
targets:
  horizon: 10
model:
  lstm_units: 96
  lstm_layers: 1
  dropout: 0.2
  xgb:
    n_estimators: 400
    max_depth: 6
    learning_rate: 0.05
backtest:
  sl_atr: 1.5
  rr_min: 2.0
  u_min: 0.9
evaluation:
  metrics: ["MAE", "RMSE", "corr"]
  split:
    train: 0.70
    val: 0.15
    test: 0.15
seed: 42